// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/src/main/resources/with_data_subject_id.proto

package org.taymyr.akka.persistence.gdpr.serialization;

public final class GDPR {
  private GDPR() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WithDataSubjectIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WithDataSubjectId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string dataSubjectId = 1;</code>
     * @return Whether the dataSubjectId field is set.
     */
    boolean hasDataSubjectId();
    /**
     * <code>required string dataSubjectId = 1;</code>
     * @return The dataSubjectId.
     */
    java.lang.String getDataSubjectId();
    /**
     * <code>required string dataSubjectId = 1;</code>
     * @return The bytes for dataSubjectId.
     */
    com.google.protobuf.ByteString
        getDataSubjectIdBytes();

    /**
     * <code>optional bytes payload = 2;</code>
     * @return Whether the payload field is set.
     */
    boolean hasPayload();
    /**
     * <code>optional bytes payload = 2;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();

    /**
     * <code>optional int32 serializerId = 3;</code>
     * @return Whether the serializerId field is set.
     */
    boolean hasSerializerId();
    /**
     * <code>optional int32 serializerId = 3;</code>
     * @return The serializerId.
     */
    int getSerializerId();

    /**
     * <code>optional string manifest = 4;</code>
     * @return Whether the manifest field is set.
     */
    boolean hasManifest();
    /**
     * <code>optional string manifest = 4;</code>
     * @return The manifest.
     */
    java.lang.String getManifest();
    /**
     * <code>optional string manifest = 4;</code>
     * @return The bytes for manifest.
     */
    com.google.protobuf.ByteString
        getManifestBytes();
  }
  /**
   * Protobuf type {@code WithDataSubjectId}
   */
  public  static final class WithDataSubjectId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WithDataSubjectId)
      WithDataSubjectIdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WithDataSubjectId.newBuilder() to construct.
    private WithDataSubjectId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WithDataSubjectId() {
      dataSubjectId_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
      manifest_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WithDataSubjectId();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WithDataSubjectId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              dataSubjectId_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              payload_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              serializerId_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              manifest_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.taymyr.akka.persistence.gdpr.serialization.GDPR.internal_static_WithDataSubjectId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.taymyr.akka.persistence.gdpr.serialization.GDPR.internal_static_WithDataSubjectId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId.class, org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId.Builder.class);
    }

    private int bitField0_;
    public static final int DATASUBJECTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object dataSubjectId_;
    /**
     * <code>required string dataSubjectId = 1;</code>
     * @return Whether the dataSubjectId field is set.
     */
    public boolean hasDataSubjectId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string dataSubjectId = 1;</code>
     * @return The dataSubjectId.
     */
    public java.lang.String getDataSubjectId() {
      java.lang.Object ref = dataSubjectId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dataSubjectId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dataSubjectId = 1;</code>
     * @return The bytes for dataSubjectId.
     */
    public com.google.protobuf.ByteString
        getDataSubjectIdBytes() {
      java.lang.Object ref = dataSubjectId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataSubjectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>optional bytes payload = 2;</code>
     * @return Whether the payload field is set.
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes payload = 2;</code>
     * @return The payload.
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    public static final int SERIALIZERID_FIELD_NUMBER = 3;
    private int serializerId_;
    /**
     * <code>optional int32 serializerId = 3;</code>
     * @return Whether the serializerId field is set.
     */
    public boolean hasSerializerId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 serializerId = 3;</code>
     * @return The serializerId.
     */
    public int getSerializerId() {
      return serializerId_;
    }

    public static final int MANIFEST_FIELD_NUMBER = 4;
    private volatile java.lang.Object manifest_;
    /**
     * <code>optional string manifest = 4;</code>
     * @return Whether the manifest field is set.
     */
    public boolean hasManifest() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string manifest = 4;</code>
     * @return The manifest.
     */
    public java.lang.String getManifest() {
      java.lang.Object ref = manifest_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          manifest_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string manifest = 4;</code>
     * @return The bytes for manifest.
     */
    public com.google.protobuf.ByteString
        getManifestBytes() {
      java.lang.Object ref = manifest_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manifest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDataSubjectId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataSubjectId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, payload_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, serializerId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, manifest_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataSubjectId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, payload_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, serializerId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, manifest_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId)) {
        return super.equals(obj);
      }
      org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId other = (org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId) obj;

      if (hasDataSubjectId() != other.hasDataSubjectId()) return false;
      if (hasDataSubjectId()) {
        if (!getDataSubjectId()
            .equals(other.getDataSubjectId())) return false;
      }
      if (hasPayload() != other.hasPayload()) return false;
      if (hasPayload()) {
        if (!getPayload()
            .equals(other.getPayload())) return false;
      }
      if (hasSerializerId() != other.hasSerializerId()) return false;
      if (hasSerializerId()) {
        if (getSerializerId()
            != other.getSerializerId()) return false;
      }
      if (hasManifest() != other.hasManifest()) return false;
      if (hasManifest()) {
        if (!getManifest()
            .equals(other.getManifest())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDataSubjectId()) {
        hash = (37 * hash) + DATASUBJECTID_FIELD_NUMBER;
        hash = (53 * hash) + getDataSubjectId().hashCode();
      }
      if (hasPayload()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
      }
      if (hasSerializerId()) {
        hash = (37 * hash) + SERIALIZERID_FIELD_NUMBER;
        hash = (53 * hash) + getSerializerId();
      }
      if (hasManifest()) {
        hash = (37 * hash) + MANIFEST_FIELD_NUMBER;
        hash = (53 * hash) + getManifest().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WithDataSubjectId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WithDataSubjectId)
        org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.taymyr.akka.persistence.gdpr.serialization.GDPR.internal_static_WithDataSubjectId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.taymyr.akka.persistence.gdpr.serialization.GDPR.internal_static_WithDataSubjectId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId.class, org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId.Builder.class);
      }

      // Construct using org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataSubjectId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        serializerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        manifest_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.taymyr.akka.persistence.gdpr.serialization.GDPR.internal_static_WithDataSubjectId_descriptor;
      }

      @java.lang.Override
      public org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId getDefaultInstanceForType() {
        return org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId.getDefaultInstance();
      }

      @java.lang.Override
      public org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId build() {
        org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId buildPartial() {
        org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId result = new org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dataSubjectId_ = dataSubjectId_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.payload_ = payload_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.serializerId_ = serializerId_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.manifest_ = manifest_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId) {
          return mergeFrom((org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId other) {
        if (other == org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId.getDefaultInstance()) return this;
        if (other.hasDataSubjectId()) {
          bitField0_ |= 0x00000001;
          dataSubjectId_ = other.dataSubjectId_;
          onChanged();
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        if (other.hasSerializerId()) {
          setSerializerId(other.getSerializerId());
        }
        if (other.hasManifest()) {
          bitField0_ |= 0x00000008;
          manifest_ = other.manifest_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasDataSubjectId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object dataSubjectId_ = "";
      /**
       * <code>required string dataSubjectId = 1;</code>
       * @return Whether the dataSubjectId field is set.
       */
      public boolean hasDataSubjectId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string dataSubjectId = 1;</code>
       * @return The dataSubjectId.
       */
      public java.lang.String getDataSubjectId() {
        java.lang.Object ref = dataSubjectId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dataSubjectId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string dataSubjectId = 1;</code>
       * @return The bytes for dataSubjectId.
       */
      public com.google.protobuf.ByteString
          getDataSubjectIdBytes() {
        java.lang.Object ref = dataSubjectId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataSubjectId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dataSubjectId = 1;</code>
       * @param value The dataSubjectId to set.
       * @return This builder for chaining.
       */
      public Builder setDataSubjectId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dataSubjectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dataSubjectId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataSubjectId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dataSubjectId_ = getDefaultInstance().getDataSubjectId();
        onChanged();
        return this;
      }
      /**
       * <code>required string dataSubjectId = 1;</code>
       * @param value The bytes for dataSubjectId to set.
       * @return This builder for chaining.
       */
      public Builder setDataSubjectIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dataSubjectId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes payload = 2;</code>
       * @return Whether the payload field is set.
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes payload = 2;</code>
       * @return The payload.
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>optional bytes payload = 2;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes payload = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000002);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      private int serializerId_ ;
      /**
       * <code>optional int32 serializerId = 3;</code>
       * @return Whether the serializerId field is set.
       */
      public boolean hasSerializerId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 serializerId = 3;</code>
       * @return The serializerId.
       */
      public int getSerializerId() {
        return serializerId_;
      }
      /**
       * <code>optional int32 serializerId = 3;</code>
       * @param value The serializerId to set.
       * @return This builder for chaining.
       */
      public Builder setSerializerId(int value) {
        bitField0_ |= 0x00000004;
        serializerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 serializerId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSerializerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serializerId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object manifest_ = "";
      /**
       * <code>optional string manifest = 4;</code>
       * @return Whether the manifest field is set.
       */
      public boolean hasManifest() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string manifest = 4;</code>
       * @return The manifest.
       */
      public java.lang.String getManifest() {
        java.lang.Object ref = manifest_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            manifest_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string manifest = 4;</code>
       * @return The bytes for manifest.
       */
      public com.google.protobuf.ByteString
          getManifestBytes() {
        java.lang.Object ref = manifest_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          manifest_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string manifest = 4;</code>
       * @param value The manifest to set.
       * @return This builder for chaining.
       */
      public Builder setManifest(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        manifest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string manifest = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearManifest() {
        bitField0_ = (bitField0_ & ~0x00000008);
        manifest_ = getDefaultInstance().getManifest();
        onChanged();
        return this;
      }
      /**
       * <code>optional string manifest = 4;</code>
       * @param value The bytes for manifest to set.
       * @return This builder for chaining.
       */
      public Builder setManifestBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        manifest_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WithDataSubjectId)
    }

    // @@protoc_insertion_point(class_scope:WithDataSubjectId)
    private static final org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId();
    }

    public static org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<WithDataSubjectId>
        PARSER = new com.google.protobuf.AbstractParser<WithDataSubjectId>() {
      @java.lang.Override
      public WithDataSubjectId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WithDataSubjectId(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WithDataSubjectId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WithDataSubjectId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.taymyr.akka.persistence.gdpr.serialization.GDPR.WithDataSubjectId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WithDataSubjectId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WithDataSubjectId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2core/src/main/resources/with_data_subj" +
      "ect_id.proto\"c\n\021WithDataSubjectId\022\025\n\rdat" +
      "aSubjectId\030\001 \002(\t\022\017\n\007payload\030\002 \001(\014\022\024\n\014ser" +
      "ializerId\030\003 \001(\005\022\020\n\010manifest\030\004 \001(\tB8\n.org" +
      ".taymyr.akka.persistence.gdpr.serializat" +
      "ionB\004GDPRH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_WithDataSubjectId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WithDataSubjectId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WithDataSubjectId_descriptor,
        new java.lang.String[] { "DataSubjectId", "Payload", "SerializerId", "Manifest", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
